spring:
  application:
    name: apollo-elevators-backend

  datasource:
    url: jdbc:postgresql://ep-ancient-voice-azj0gtoq.c-3.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_FU5hYwtveqo3

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

app:
  master-key: iXYPQftcide0XlqLzyN4ccWbMaw/AxsodHjMNIwn7O4=

logging:
  level:
    com.apollo.elevators: INFO

springdoc:
  api-docs:
    path: /v3/api-docs

  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    operations-sorter: method
    tags-sorter: alpha

  default-consumes-media-type: application/json
  default-produces-media-type: application/json
