ALTER TABLE customer
    DROP COLUMN IF EXISTS remarks;

ALTER TABLE lift
    ADD COLUMN IF NOT EXISTS door_type VARCHAR(20),
    ADD COLUMN IF NOT EXISTS machine_type VARCHAR(100),
    ADD COLUMN IF NOT EXISTS machine_name VARCHAR(100),
    ADD COLUMN IF NOT EXISTS kw NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS amps NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS speed NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS voltage NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS frequency NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS osg_type VARCHAR(100),
    ADD COLUMN IF NOT EXISTS rated_speed NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS tripping_speed NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS is_ups_present BOOLEAN,
    ADD COLUMN IF NOT EXISTS ups_type VARCHAR(100),
    ADD COLUMN IF NOT EXISTS kva NUMERIC(10,2);

ALTER TABLE amc_contract
    ADD COLUMN IF NOT EXISTS contract_type VARCHAR(20);

ALTER TABLE amc_contract
    DROP COLUMN IF EXISTS amc_type,
    DROP COLUMN IF EXISTS terms_and_conditions,
    DROP COLUMN IF EXISTS remarks;
